export const FIREBASE_CONFIG = {
  apiKey: 'AIzaSyCtQ_-1CnzEUKNENls7FC8bptg9XlkLBRE',
  authDomain: 'unsa-indicadores.firebaseapp.com',
  projectId: 'unsa-indicadores',
  storageBucket: 'unsa-indicadores.firebasestorage.app',
  messagingSenderId: '54369861268',
  appId: '1:54369861268:web:71478732cfd68211f27e81',
};

/**
 * La fuente de verdad de roles y permisos vive en src/lib/roles.ts.
 * Este archivo se mantiene por compatibilidad; cualquier cambio de roles o
 * permisos debe hacerse en roles.ts.
 */
export const ADMIN_EMAILS = ['lmendoza@unsa.edu.pe'];

export const ROLE_MAP = {
  'lmendoza@unsa.edu.pe': { role: 'admin', facultad: null, escuela: null, label: 'Administrador' },
  'wvaldez@@unsa.edu.pe': { role: 'admin', facultad: null, escuela: null, label: 'Administrador' },
  'esiug@unsa.edu.pe': { role: 'admin', facultad: null, escuela: null, label: 'Administrador' },
  'jleonq@unsa.edu.pe': { role: 'admin', facultad: null, escuela: null, label: 'Administrador' },
  'vrac@unsa.edu.pe': { role: 'autoridad', facultad: null, escuela: null, label: 'Autoridad' },
  'rectorado@unsa.edu.pe': { role: 'autoridad', facultad: null, escuela: null, label: 'Autoridad' },
  'vrai@unsa.edu.pe': { role: 'autoridad', facultad: null, escuela: null, label: 'Autoridad' },
  'fad@unsa.edu.pe':        { role: 'decano', facultad: 'ADMINISTRACIÓN', escuela: null, label: 'Decano' },
  'fagronomia@unsa.edu.pe': { role: 'decano', facultad: 'AGRONOMÍA', escuela: null, label: 'Decano' },
  'fau@unsa.edu.pe':        { role: 'decano', facultad: 'ARQUITECTURA Y URBANISMO', escuela: null, label: 'Decano' },
  'fcb@unsa.edu.pe':        { role: 'decano', facultad: 'CIENCIAS BIOLÓGICAS', escuela: null, label: 'Decano' },
  'fccf@unsa.edu.pe':       { role: 'decano', facultad: 'CIENCIAS CONTABLES \u00a0Y FINANCIERAS', escuela: null, label: 'Decano' },
  'educacion@unsa.edu.pe':  { role: 'decano', facultad: 'CIENCIAS DE LA EDUCACIÓN', escuela: null, label: 'Decano' },
  'fchs@unsa.edu.pe':       { role: 'decano', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: null, label: 'Decano' },
  'fcnf@unsa.edu.pe':       { role: 'decano', facultad: 'CIENCIAS NATURALES Y FORMALES', escuela: null, label: 'Decano' },
  'fderecho@unsa.edu.pe':   { role: 'decano', facultad: 'DERECHO', escuela: null, label: 'Decano' },
  'feconomia@unsa.edu.pe':  { role: 'decano', facultad: 'ECONOMÍA', escuela: null, label: 'Decano' },
  'fen@unsa.edu.pe':        { role: 'decano', facultad: 'ENFERMERÏE', escuela: null, label: 'Decano' },
  'ffh@unsa.edu.pe':        { role: 'decano', facultad: 'FILOSOFÍA Y HUMANIDADES', escuela: null, label: 'Decano' },
  'fggm@unsa.edu.pe':       { role: 'decano', facultad: 'INGENIERÍA GEOLÓGICA, GEOFÍSICA Y MINAS', escuela: null, label: 'Decano' },
  'fic@unsa.edu.pe':        { role: 'decano', facultad: 'INGENIERÍA CIVIL', escuela: null, label: 'Decano' },
  'fip@unsa.edu.pe':        { role: 'decano', facultad: 'INGENIERÍA DE PROCESOS', escuela: null, label: 'Decano' },
  'fips@unsa.edu.pe':       { role: 'decano', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: null, label: 'Decano' },
  'facmed@unsa.edu.pe':     { role: 'decano', facultad: 'MEDICINA', escuela: null, label: 'Decano' },
  'fprriicc@unsa.edu.pe':   { role: 'decano', facultad: 'PSICOLOGÍA, RR.II. Y CS. DE LA COMUNICACIÓN', escuela: null, label: 'Decano' },
  'jleonq@unsa.edu.pe': { role: 'director', facultad: 'CIENCIAS BIOLÓGICAS', escuela: 'BIOLOGÍA', label: 'Director de Escuela' },
  'administracion@unsa.edu.pe':      { role: 'director', facultad: 'ADMINISTRACIÓN', escuela: 'ADMINISTRACIÓN', label: 'Director de Escuela' },
  'alimentaria@unsa.edu.pe':         { role: 'director', facultad: 'INGENIERÍA DE PROCESOS', escuela: 'INGENIERÍA DE INDUSTRIAS ALIMENTARIAS', label: 'Director de Escuela' },
  'ambiental@unsa.edu.pe':           { role: 'director', facultad: 'INGENIERÍA DE PROCESOS', escuela: 'INGENIERÍA AMBIENTAL', label: 'Director de Escuela' },
  'antropologia@unsa.edu.pe':        { role: 'director', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: 'ANTROPOLOGÍA', label: 'Director de Escuela' },
  'artes@unsa.edu.pe':               { role: 'director', facultad: 'FILOSOFÍA Y HUMANIDADES', escuela: 'ARTES', label: 'Director de Escuela' },
  'bancayseguros@unsa.edu.pe':       { role: 'director', facultad: 'ADMINISTRACIÓN', escuela: 'BANCA Y SEGUROS', label: 'Director de Escuela' },
  'biologia@unsa.edu.pe':            { role: 'director', facultad: 'CIENCIAS BIOLÓGICAS', escuela: 'BIOLOGÍA', label: 'Director de Escuela' },
  'ccomunicacion@unsa.edu.pe':       { role: 'director', facultad: 'PSICOLOGÍA, RR.II. Y CS. DE LA COMUNICACIÓN', escuela: 'CIENCIAS DE LA COMUNICACIÓN', label: 'Director de Escuela' },
  'civil@unsa.edu.pe':               { role: 'director', facultad: 'INGENIERÍA CIVIL', escuela: 'INGENIERÍA CIVIL', label: 'Director de Escuela' },
  'contabilidad@unsa.edu.pe':        { role: 'director', facultad: 'CIENCIAS CONTABLES \u00a0Y FINANCIERAS', escuela: 'CONTABILIDAD', label: 'Director de Escuela' },
  'dadp@unsa.edu.pe':                { role: 'director', facultad: 'DERECHO', escuela: 'DERECHO', label: 'Director de Escuela' },
  'dadpub@unsa.edu.pe':              { role: 'director', facultad: 'DERECHO', escuela: 'DERECHO', label: 'Director de Escuela' },
  'dae@unsa.edu.pe':                 { role: 'director', facultad: 'ECONOMÍA', escuela: 'ECONOMÍA', label: 'Director de Escuela' },
  'damed@unsa.edu.pe':               { role: 'director', facultad: 'MEDICINA', escuela: 'MEDICINA', label: 'Director de Escuela' },
  'enfermeria@unsa.edu.pe':          { role: 'director', facultad: 'ENFERMERÏA', escuela: 'ENFERMERÍA', label: 'Director de Escuela' },
  'epcc@unsa.edu.pe':                { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'CIENCIA DE LA COMPUTACIÓN', label: 'Director de Escuela' },
  'epf@unsa.edu.pe':                 { role: 'director', facultad: 'CIENCIAS NATURALES Y FORMALES', escuela: 'FÍSICA', label: 'Director de Escuela' },
  'epie@unsa.edu.pe':                { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA ELECTRÓNICA', label: 'Director de Escuela' },
  'epiel@unsa.edu.pe':               { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA ELÉCTRICA', label: 'Director de Escuela' },
  'epii@unsa.edu.pe':                { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA INDUSTRIAL', label: 'Director de Escuela' },
  'epis@unsa.edu.pe':                { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA DE SISTEMAS', label: 'Director de Escuela' },
  'epit@unsa.edu.pe':                { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA EN TELECOMUNIICACIONES', label: 'Director de Escuela' },
  'fagronomia_secacad@unsa.edu.pe':  { role: 'director', facultad: 'AGRONOMÍA', escuela: 'INGENIERÍA AGRONÓMICA', label: 'Director de Escuela' },
  'fau_epa@unsa.edu.pe':             { role: 'director', facultad: 'ARQUITECTURA Y URBANISMO', escuela: 'ARQUITECTURA', label: 'Director de Escuela' },
  'filosofia@unsa.edu.pe':           { role: 'director', facultad: 'FILOSOFÍA Y HUMANIDADES', escuela: 'FILOSOFÍA', label: 'Director de Escuela' },
  'finanzas@unsa.edu.pe':            { role: 'director', facultad: 'CIENCIAS CONTABLES \u00a0Y FINANCIERAS', escuela: 'FINANZAS', label: 'Director de Escuela' },
  'geofisica@unsa.edu.pe':           { role: 'director', facultad: 'INGENIERÍA GEOLÓGICA, GEOFÍSICA Y MINAS', escuela: 'INGENIERÍA GEOFÍSICA', label: 'Director de Escuela' },
  'geologia@unsa.edu.pe':            { role: 'director', facultad: 'INGENIERÍA GEOLÓGICA, GEOFÍSICA Y MINAS', escuela: 'INGENIERÍA GEOLÓGICA', label: 'Director de Escuela' },
  'gestion@unsa.edu.pe':             { role: 'director', facultad: 'ADMINISTRACIÓN', escuela: 'GESTIÓN', label: 'Director de Escuela' },
  'historia@unsa.edu.pe':            { role: 'director', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: 'HISTORIA', label: 'Director de Escuela' },
  'iquimica@unsa.edu.pe':            { role: 'director', facultad: 'INGENIERÍA DE PROCESOS', escuela: 'INGENIERÍA QUÍMICA', label: 'Director de Escuela' },
  'literatura@unsa.edu.pe':          { role: 'director', facultad: 'FILOSOFÍA Y HUMANIDADES', escuela: 'LITERATURA Y LINGÜÍSTICA', label: 'Director de Escuela' },
  'marketing@unsa.edu.pe':           { role: 'director', facultad: 'ADMINISTRACIÓN', escuela: 'MARKETING', label: 'Director de Escuela' },
  'matematicas@unsa.edu.pe':         { role: 'director', facultad: 'CIENCIAS NATURALES Y FORMALES', escuela: 'MATEMÁTICAS', label: 'Director de Escuela' },
  'materiales@unsa.edu.pe':          { role: 'director', facultad: 'INGENIERÍA DE PROCESOS', escuela: 'INGENIERÍA DE MATERIALES', label: 'Director de Escuela' },
  'mecanica@unsa.edu.pe':            { role: 'director', facultad: 'INGENIERÍA DE PRODUCCIÓN Y SERVICIOS', escuela: 'INGENIERÍA MECÁNICA', label: 'Director de Escuela' },
  'metalurgia@unsa.edu.pe':          { role: 'director', facultad: 'INGENIERÍA DE PROCESOS', escuela: 'INGENIERÍA METALÚRGICA', label: 'Director de Escuela' },
  'minas@unsa.edu.pe':               { role: 'director', facultad: 'INGENIERÍA GEOLÓGICA, GEOFÍSICA Y MINAS', escuela: 'INGENIERÍA  DE MINAS', label: 'Director de Escuela' },
  'nutricion@unsa.edu.pe':           { role: 'director', facultad: 'CIENCIAS BIOLÓGICAS', escuela: 'CIENCIAS DE LA NUTRICIÓN', label: 'Director de Escuela' },
  'pesquera@unsa.edu.pe':            { role: 'director', facultad: 'CIENCIAS BIOLÓGICAS', escuela: 'INGENIERÍA PESQUERA', label: 'Director de Escuela' },
  'psicologia@unsa.edu.pe':          { role: 'director', facultad: 'PSICOLOGÍA, RR.II. Y CS. DE LA COMUNICACIÓN', escuela: 'PSICOLOGÍA', label: 'Director de Escuela' },
  'quimica@unsa.edu.pe':             { role: 'director', facultad: 'CIENCIAS NATURALES Y FORMALES', escuela: 'QUÍMICA', label: 'Director de Escuela' },
  'rrii@unsa.edu.pe':                { role: 'director', facultad: 'PSICOLOGÍA, RR.II. Y CS. DE LA COMUNICACIÓN', escuela: 'RELACIONES INDUSTRIALES', label: 'Director de Escuela' },
  'sanitaria@unsa.edu.pe':           { role: 'director', facultad: 'INGENIERÍA CIVIL', escuela: 'INGENIERÍA SANITARIA', label: 'Director de Escuela' },
  'sociologia@unsa.edu.pe':          { role: 'director', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: 'SOCIOLOGÍA', label: 'Director de Escuela' },
  'trabajo_social@unsa.edu.pe':      { role: 'director', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: 'TRABAJO SOCIAL', label: 'Director de Escuela' },
  'turismo@unsa.edu.pe':             { role: 'director', facultad: 'CIENCIAS HISTÓRICO SOCIALES', escuela: 'TURISMO Y HOTELERÍA', label: 'Director de Escuela' },
} as const;
